### ISSUE TITLE
package.json contains private dependency

### ISSUE THREAD

**Issue by blaues0cke** [readwritetools/copyright#1]
So its not possible to install:

![image](https://user-images.githubusercontent.com/5159398/87441851-e224aa80-c5f3-11ea-9a48-d532f21a3ee1.png)

This is caused by this line in https://github.com/readwritetools/copyright/blob/master/package.json:

```
  "dependencies": {
    "joezone": "git+ssh://root@nk024:/keep/joezone#"
  },
```

**Comment by joehonton** [comment]
dependency has been fixed
